### ISSUE TITLE
Krace - Users are unable to receive any rewards if they are blacklisted by any of the reward tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#13]
Krace

medium

# Users are unable to receive any rewards if they are blacklisted by any of the reward tokens

## Summary

Users cannot get any rewards once they are only blacklisted by one `_rewardsTokens`.

## Vulnerability Detail

When claiming rewards, users must claim all rewards for all `_rewardTokens`. If a user is blacklisted by any one of the `_rewardTokens` (such as *USDT*), he cannot receive rewards for other `rewardTokens` because the `safeTransfer` will always revert the `getRewards` function.

```solidity
    /// @notice Claim rewards for all possible _rewardTokens.
    function getRewards() public updateReward(_msgSender()) {
        for (uint256 i = 0; i < rewardTokens.length; i++) { _getRewardAt(i); }
    }
    
    /// @notice Claim rewards for a specific _rewardToken.
    /// @param index The index to claim, corresponds to a given index of rewardToken[].
    function _getRewardAt(uint256 index) internal nonReentrant {
        address _rewardsToken = rewardTokens[index];
        uint256 reward = rewards[_msgSender()][_rewardsToken];
        if (reward > 0) {
            rewards[_msgSender()][_rewardsToken] = 0;
            IERC20(_rewardsToken).safeTransfer(_msgSender(), reward);
            emit RewardDistributed(_msgSender(), _rewardsToken, reward);
        }
    }
```

## Impact

Users cannot get any rewards once they are blacklisted by any one of the `_rewardsTokens`.

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/ZivoeRewards.sol#L281-L295

## Tool used

Manual Review

## Recommendation

Allow users to get rewards via specified rewardTokens.

**Comment by pseudonaut** [comment]
Not relevant

**Comment by ZdravkoHr** [comment]
Escalate

According to the docs: 
`User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.`

There is no harm to the protocol, so I think it should be Low

**Comment by panprog** [comment]
I believe what the rules mean is that if some token blacklisted the user and user can't receive anything in this token from the protocol, this is invalid. However, this issue is that the user can't get the *other* reward tokens when only 1 of them blacklists the user. So while it's true that user can't receive rewards due to being blacklisted, it's still unfair and loss of funds of the other reward tokens for the user. That's why it should remain valid medium.

**Comment by ZdravkoHr** [comment]
In the end it's still a loss for the user only. I don't think the rule is ambiguous. Any other details around how is it a loss for the user are context dependent and shouldn't be taken into consideration, given there is no real harm for any other party

**Comment by amankakar** [comment]
>In the end it's still a loss for the user only. I don't think the rule is ambiguous. Any other details around how is it a loss for the user are context dependent and shouldn't be taken into consideration, given there is no real harm for any other party

The users are eligible to receive the rewards for other tokens but they can not because the user is blacklisted by only one token. so in this case the normal flow The user should be able to withdraw rewards for other tokens.
How can this be low ? if the rest of rewards can not be withdrawn due to 1 token rewards.

**Comment by BiasedMerc** [comment]
> > In the end it's still a loss for the user only. I don't think the rule is ambiguous. Any other details around how is it a loss for the user are context dependent and shouldn't be taken into consideration, given there is no real harm for any other party
> 
> The users are eligible to receive the rewards for other tokens but they can not because the user is blacklisted by only one token. so in this case the normal flow The user should be able to withdraw rewards for other tokens. How can this be low ? if the rest of rewards can not be withdrawn due to 1 token rewards.

The point being outlined is the sherlock rules:
> According to the docs:
> User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.

This impact is only for the blacklisted user, so according to the docs this should be invalid. If a user being blacklisted caused rewards to not be distributed to other users, then this would be valid accoring to this rule. But this specific issue only concerns the blacklisted user themselves.

**Comment by RealLTDingZhen** [comment]
Hi @panprog I believe #666 is a dup of this. It noticed that if PYUSD admin freeze OCY_Convex_C, all other avaliable token yields will be unaccessable.

**Comment by amankakar** [comment]
> The point being outlined is the sherlock rules:
> 
> > According to the docs:
> > User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.
> 
> This impact is only for the blacklisted user, so according to the docs this should be invalid. If a user being blacklisted caused rewards to not be distributed to other users, then this would be valid accoring to this rule. But this specific issue only concerns the blacklisted user themselves.

The Themselves should be in context of that token not other tokens.

**Comment by zarkk01** [comment]
Hey,

**Comment by zarkk01** [comment]
We should focus on "causing harm only to themselves".  User gets blacklisted on USDT -> Not able to withdraw(USDT or whatever coin, this is the definition of causing harm to myself). What I mean is that "causing harm" is a general term and thats why all these problems fall under this. It has not to do with not be able to withdraw USDT, it has to do with causing harm and causing harm means whatever is not good for the user(in our case not withdrawing funds of whatever token). So basically, when a user gets blacklisted and can not withdraw rewards of ANY token is causing harm to himself... so invalid.

**Comment by amankakar** [comment]
> We should focus on "causing harm only to themselves". User gets blacklisted on USDT -> Not able to withdraw(USDT or whatever coin, this is the definition of causing harm to myself). What I mean is that "causing harm" is a general term and thats why all these problems fall under this. It has not to do with not be able to withdraw USDT, it has to do with causing harm and causing harm means whatever is not good for the user(in our case not withdrawing funds of whatever token). So basically, when a user gets blacklisted and can not withdraw rewards of ANY token is causing harm to himself... so invalid.

and the Role of Sherlock says that
> User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.

The Role is for the case where due to one user got blacklisted, the other users should be able to withdraw their tokens. As we have seen in a lot of protocols they distribute the token to the users in a single transaction. like they iterate over all the users and transfer their rewards or whatever tokens to users, so in this case if one of user is blacklisted all the other users will not be able to receive their token that's why it is valid. the reason for this validity is that user A can not receive token A because user B is Blacklisted by Token A. 
But in the case you can apply the same thing Here the user is 1 but the tokens are many.  Now User A can not receive token A because User A is Blacklist by token B. There must be some way that User A withdraw rewards for Token B.

The harm is related to single user but tokens are different. Imagine a case where I say you can not receive $ on Because you are blacklisted by €. That why it is valid.

**Comment by marchev** [comment]
The primary concern here extends beyond just a user being blacklisted—it's the wider implications stemming from the flawed reward distribution mechanism in the contract.

This flaw implies that any failure (such as a malfunction in a stablecoin contract) could lead users to face similar issues. Essentially, the inability to withdraw rewards from one token should not obstruct withdrawals from other tokens. The issue of being blacklisted is just one example of a potential trigger for this problem.

Given these considerations, this issue should indeed be acknowledged as valid.

**Comment by marchev** [comment]
@panprog I suggest selecting #279 as the main report because it accurately addresses the fact that the issue exists in both `ZivoeRewards` and `ZivoeRewardsVesting`. The current report overlooks the shared implementation between these contract, reporting the issue only for `ZivoeRewards`, potentially leaving some vulnerabilities unaddressed.

**Comment by WangSecurity** [comment]
Is there any impact to the protocol or other users if not all of the rewards are sent? For example, we distribute rewards in USDC and ZVE, the user is blacklisted for USDC, hence they cannot withdraw rewards for both USDC and ZVE and they're stuck in the contract. Does it effect contract's functionality in any way, when we want to set new rewards for example? Or the protocol works without any problem and it's only the blacklisted user who is harmed?

**Comment by marchev** [comment]
@WangSecurity The impact depends on the scenario. If a specific user is blacklisted, only that user is affected, and they won't be able to withdraw any rewards, including those in other tokens.

However, if the ZivoeRewards contract is blacklisted for any rewardTokens, the entire reward distribution system will fail for all users, leaving all funds stuck in the contract. Additionally, there is no possibility to remove a token from rewardTokens, which exacerbates the issue further.

For instance, if DAI's emergency shutdown is activated, it will prevent reward claims for all tokens for all users. Essentially, any event that disrupts a token transfer will trigger this issue.

**Comment by WangSecurity** [comment]
Firstly, I believe we should assume protocol's contracts won't get blacklisted. Secondly, DAI's shutdown or other tokens pausing their functionality is a different issue, rather than this one about users being blacklisted.

Since only the blacklisted user is effected, I believe this rule should be applied here:

> User Blacklist: User getting blacklisted by a token/contract causing harm only to themselves is not a valid medium/high.

I understand that reward in other tokens are also effected (for example user is blacklisted in USDC and cannot withdraw rewards for any other token as well) and it's a good precedent for changing the phrasing of the rule. But with current phrasing, I believe it should be correctly applied here.

Planning to accept the escalation and invalidate the report.

**Comment by amankakar** [comment]
Hi @WangSecurity , I don't think that this rules is applied here Because The rule is specific towards single token and here the user can not receive other tokens as well . It is an edge case which is not covered by this rule. There for the Escalation should be rejected.
As you have already mentioned that 
> I understand that reward in other tokens are also effected (for example user is blacklisted in USDC and cannot withdraw rewards for any other token as well) and it's a good precedent for changing the phrasing of the rule. But with current phrasing, I believe it should be correctly applied here.

Thanks for your effort.

**Comment by marchev** [comment]
@WangSecurity I understand your point and largely agree with your reasoning. However, I'd like to ask for a more pragmatic view in this particular instance. The scope of the reported issue extends beyond just the blacklisted token, blocking any reward withdrawals for the user, which significantly impacts their ability to interact with the protocol.

It's generally accepted that the pattern used here is considered a bad practice, as it is susceptible to vulnerabilities that may affect users beyond the scope of a single token, given the atomic nature of Ethereum transactions.

As with other rules, there are instances where context-specific precedents have been set. This issue, given its broader implications, might be one such case where a different approach could be warranted.

That said, we will respect and support the final decision you make.

**Comment by WangSecurity** [comment]
Firstly:

> I don't think that this rules is applied here Because The rule is specific towards single token and here the user can not receive other tokens as well . It is an edge case which is not covered by this rule

The rule doesn't say that it's about one token, the rule says that if the user getting blacklisted only causes harm to themselves, the issue is not valid M/H, which is situation here.

Secondly, 

> The scope of the reported issue extends beyond just the blacklisted token, blocking any reward withdrawals for the user, which significantly impacts their ability to interact with the protocol.

I totally understand, but the situation here is actually what is described by the rule: user's blacklisted and only harms themselves. Hence, I believe it's fair to make it invalid under the current rules. I see that we can say it has broader implications, but still the rule should be applied here.

**Comment by rbserver** [comment]
Hi @WangSecurity, thanks for judging!

There are situations like DAI's emergency shutdown mentioned in https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/13#issuecomment-2112199300 and also USDC and USDT's contracts being paused mentioned in my report https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/486. These situations affect all users, not just one user, and no blocklist is involved.

The official contest page, https://audits.sherlock.xyz/contests/280, lists the question: `In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.` The sponsor's answer is `Not acceptable`. This indicates that this risk of external contracts pausing is not acceptable by the Zivoe protocol.

Given these reasons, would at least the reports that mentioned about the risk of the external token contracts being paused be considered as a medium risk?

**Comment by WangSecurity** [comment]
Firstly, as I understand, the core issue of this report is that one user will be blacklisted, which is perfectly suitable for the rule about blacklisted users. Secondly, as I understand #486 is incorrectly grouped here, since it identifies a different core issue of completely pausing the token.

Hence, decision remains the same. Accept the escalation and invalidate the issue.

**Comment by marchev** [comment]
@WangSecurity I am writing to request a reconsideration of your decision.

The root cause of the problem highlighted in both #486 and #13 is fundamentally the same: a failure in the `safeTransfer()` call makes all other rewards unclaimable. This underlying issue leads to different attack paths but is essentially the same vulnerability. The attack paths are different (blacklisting, token pausing), however the vulnerability is that the implementation does not handle properly the fact that for one of the tokens a failure would block claiming all other rewards.

According to Sherlock’s duplication rules, scenarios that derive from the same root vulnerability should be considered duplicates. The rules state:

> **Scenario A:**
There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attack paths:
>
> **B** -> high severity path
> **C** -> medium severity attack path/just identifying the vulnerability.
> Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put together as duplicates.

Having said that, either both #13 and #486 must be valid or neither of them.

**Comment by WangSecurity** [comment]
#486 I believe identifies two issues:

1. Blocklisting user: invalid due to rules (harms only the user themselves)
2. Token Shutdown: external admins pausing their contract harming all the users, which we have to validate based on README (if you think it's unfair, I agree, but based on README we have to do that).

Hence, I believe this report and its duplicates (despite #486 ) has to be invalidated based on the rule of blacklisted user (the user only harms themselves), while #486 has to be duplicated with #657.

And again, I totally understand, if it seems unfair to you, but based on this specific contest's README and Sherlock's rules, I have to make these decisions.

Decision remains the same, planning to accept the escalation and leave the issue as it is.

**Comment by marchev** [comment]
@WangSecurity Your decision will be respected. However, I believe it is important to highlight the following based on Sherlock's Criteria for Issue Validity when assessing duplicates:

According to the criteria, what matters is the "root cause/error/vulnerability A in the code." This means the vulnerability is an inherent characteristic of the code under review. In this particular example, the vulnerability is that rewards are distributed in an all-or-nothing fashion which is vulnerable in case any of the transfers fail. This vulnerability can lead to various attack paths (blacklisting user, token shutdown, etc.) The criteria explicitly state that if the "root cause/error/vulnerability A in the code" leads to two attack paths, and "both B & C would not have been possible if error A did not exist in the first place," then both B & C should be considered duplicates.

Therefore, I appeal to you once again to consider making both issues either valid or invalid according to [Sherlock's Criteria for Issue Validity](https://docs.sherlock.xyz/audits/judging/judging#ix.-duplication-rules).

**Comment by WangSecurity** [comment]
Yeah, I understand the rules, but as I've said, there two different root causes for the transfer to rever and I explained them [here](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/13#issuecomment-2118442277). But, #486 shows both of them, hence, it can be duplicated with #657 with a core issue of external admins are rugging Zivoe (either blocking their functionality or stealing funds), cause the complete token shutdown will impact the entire protocol. While blocking a user, only harms that user, which is invalid by the rules.

I agree that in both cases transfer doesn't work, but there are two different causes for it and in one of them it impacts the entire protocol and in the other one it impacts only one user. Yes, we can say that the token admins decide to block every user and I believe it's suitable to the core issue of external admins completely rugging Zivoe (either blocking their functionality or stealing funds).

Hope for your understanding, but if you still disagree with my words or don't understand them, please say which ones, specifically, are still not making sense. But, still decision remains the same, accept the escalation and invalidate the reports.

**Comment by marchev** [comment]
@WangSecurity Thank you for your detailed response. While I understand your perspective, I respectfully disagree.

According to Sherlock's Criteria for Issue Validity, the root cause/error/vulnerability must be part of the codebase we are reviewing. This is clear from the wording: "There is a root cause/error/vulnerability A **in the code**. This vulnerability A -> leads to two attack paths." Therefore, the root cause/error/vulnerability cannot be external to the code. In your argument, you claim that the root causes are different, but they are not. The triggers may be different (as triggers can be external), but the vulnerability remains the same in both cases: improper handling of failing transfers in a for loop responsible for distributing user rewards.

As mentioned, I will respect your decision regardless. However, I believe the Sherlock rules are not being applied fairly in this instance.

I hope you understand my viewpoint. If you still disagree, I suggest we conclude this discussion to avoid further unnecessary debate.

**Comment by marchev** [comment]
To add to my point, the validity of this issue should be confirmed as per the reasoning provided by @panprog:

> But on the other hand, for a true trustless execution, no token should influence the other tokens, so in this sense the user is unable to claim valid tokens he is not blacklisted for, so a loss of funds for the user and valid medium.

**Comment by WangSecurity** [comment]
@marchev I see your point, yes, the problem is that the transfer is not handled correctly. But it can be cause by two different reasons, that is why I believe these are two different issues, that I've expressed above. I genuinely believe that one user being blacklisted and the token being paused completely are two different issues. But, yes, both of the lead to transfer reverting, but the reason for that is completely different and the impact is different as well (only one user hardmed and the entire protocol harmed, respectively). Moreover, if we fix the issue and allow the  user to receive rewards in other tokens, it won't fix the problem when the token functionality is paused and causes a lot more significant impact.

The point from panprog that you quoted, also was addressed above: it still applies to the rule that the only harmed user is the blacklisted one, hence, should be invalid based on the rules.

Decision remains the same, accept the escalation and invalidate the issue.

**Comment by marchev** [comment]
Thanks for taking the time to discuss into details!

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/13/#issuecomment-2105647906): accepted
