### ISSUE TITLE
JigglypuffAndPikachu - Overwriting `basis` even when `amount <= basis` Leads to Overallocation of Rewards

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#213]
JigglypuffAndPikachu

high

# Overwriting `basis` even when `amount <= basis` Leads to Overallocation of Rewards

## Summary

Every time the USDC in the `ZVE/USDC` pool decreases between two `forwardYield` calls, the loss is "written off" due to the line but every time the USDC amount increases it is rewarded as yield. 

## Vulnerability Detail

The easiest way to explain this vulenarbility is through an example

Take this scenario:

Let's say there is an initial USDC deposit. Then there are 3 sequential yield distribution calls, with no other changes to the deposit:

In 1st yield distribution call the `USDC/ZVE` ratio is 100/100
In 2nd yield distribution call the `USDC/ZVE` ratio is 50/200
In 3nd yield distribution call the `USDC/ZVE` ratio is 100/200 again.

We can see that from the 1st to 3rd yield distribution, the USDC in the pool is exactly the same. There has been no total USDC gain and in our hypothetical example no yield gained. Logically, no yield should be distributed.

In Ziove, during the 2nd yield distribution call, the previous basis of `100` is replaced with the new basis of `50`.

```solidity
        if (amount > basis) { _forwardYield(amount, lp); }
        //replaces the basis stored
        (basis,) = fetchBasis();
```

Then in the 3rd distribute yield call, the `amount` is `100`  when `50`, which is basically registered as `50` USDC gain to be distributed to users.

The correct logic is to put `(basis,) = fetchBasis();` within the basis, so the basis is only updated when yield is forwaded.

## Impact

Severe overallocation of yield due to losses between yield distribution periods being written off and gains between periods being distributed

## Code Snippet

https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L287-L305

## Tool used

Manual Review

## Recommendation

The  correct logic is to put the `basis` overwriting inside the `if` statement rather than outside, like this:

```solidity
if (amount > basis) { 
     _forwardYield(amount, lp); 
    (basis,) = fetchBasis();
}
```
However there may be other problems with basis that also need to be fixed due to seperate issues.

**Comment by pseudonaut** [comment]
This isn't how basis is calculated, not valid

**Comment by Banditx0x** [comment]
Escalate on behalf of JigglypuffAndPikachu.

I believe this is seperate from #296 and it's dupes which focus on the basis being manipulatable.

This issue describes how even if all `forwardYield` calls occur through flashbots,and even if the Uniswap pool is never purposely manipulated, there is still an overallocation of rewards.

The root issue is that when `basis` decreases due to an exchange rate decrease in `USDC/ZVE`, the previous basis is overwritten. This results in rewards being distributed even if the USDC amount has gone down. For example in a sequence when the USDC balance goes through this sequence on sequential `forwardYield` calls:

1. 1000
2. 500
3. 600

Let's say those changes are purely due to reserve changes in the Uniswap pool, with no deposits and withdrawals occuring in between. Yield is still distributed as the basis increased from steps `2` to `3` USDC, even though the overall USDC has decreased since the beginning.

Only overwriting the basis in the `if` statement will ensure that USDC is only distributed when the amount exceeds the balance after the previous time yield was distributed.

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of JigglypuffAndPikachu.
> 
> I believe this is seperate from #296 and it's dupes which focus on the basis being manipulatable.
> 
> This issue describes how even if all `forwardYield` calls occur through flashbots,and even if the Uniswap pool is never purposely manipulated, there is still an overallocation of rewards.
> 
> The root issue is that when `basis` decreases due to an exchange rate decrease in `USDC/ZVE`, the previous basis is overwritten. This results in rewards being distributed even if the USDC amount has gone down. For example in a sequence when the USDC balance goes through this sequence on sequential `forwardYield` calls:
> 
> 1. 1000
> 2. 500
> 3. 600
> 
> Let's say those changes are purely due to reserve changes in the Uniswap pool, with no deposits and withdrawals occuring in between. Yield is still distributed as the basis increased from steps `2` to `3` USDC, even though the overall USDC has decreased since the beginning.
> 
> Only overwriting the basis in the `if` statement will ensure that USDC is only distributed when the amount exceeds the balance after the previous time yield was distributed. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I see your point and fully agree that the logic of such yield distribution is quite strange and not obvious and inflates the yield distribution quite a lot. However, I've discussed this with developers and this is what they say:

> Well a large part of this locker is offering liquidity for ZVE, as the DAO will have a good portion which it should sell off eventually. The USDC it stakes against it, if distributed due to back and forth movement, is simply passed through the protocol as yield after 20 distributions and then however much ZVE not sold returns to the DAO
The basis is ultimately a means of accounting for if ZVE price increases drastically from liquidity in locker, those net-gains are distributed as yield back to protocol
If it crab-walks then the accounting is simply going to wind-down the position until all ZVE is sold and principal is distributed / returned to DAO
But still accomplishing the goal of creating liquidity for ZVE to purchase

So this is by design and intended. Moreover, this exact issue might even be invalid since the basis for the #296 is ability to manipulate this to distribute very inflated yield, while what this issue describes is just normal expected behavior (even if it looks strange).

**Comment by Banditx0x** [comment]
This behavior is incredibly strange. The sponsor clearly indicated that they did not believe distribution worked as the issue described by the [initial reply on this issue](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/213#issuecomment-2081503305):

> This isn't how basis is calculated, not valid

Additionally, I had brought this up in a private thread and myself and the sponsor had very different understandings of how basis worked.

So either:

1. this issue is technically incorrect or:
2. this issue correctly describes how basis calculations play out which is different from how the sponsor initially intended.

The initial comment by the sponsor, and the bizareness of the distribution logic means that this issue cannot be labelled "technically correct but intended by design".

**Comment by WangSecurity** [comment]
I might need explanation how the basis works and how it is calculated, cause as I understand the example in this report, it's indeed incorrect. It gives example of chaing ratio of USDC/ZVE and when it becomes 50/200, basis becomes 50, then it's increased to 100 and basis becomes 100 as well.

But, if we look at the formula at [`fetchBasis`](https://github.com/sherlock-audit/2024-03-zivoe/blob/d4111645b19a1ad3ccc899bea073b6f19be04ccd/zivoe-core-foundry/src/lockers/OCL/OCL_ZVE.sol#L336) then it's not just equal to the amount of USDC, it's `amount of LP tokens owned by OCL_ZVE * USDC owned by OCL_ZVE / total supply of LP tokens`. 

As I understand the scenario of changes between basis equal to changes of USDC in the pool technically can occur, as explained in the escalation comment. So, additionally, I would like to ask @Banditx0x to provide the screenshot of how the sponsor explained the basis, cause as of now it indeed looks like the intended design. 

And if we treat it as a separate issue from #296 (for simplicity) can you clarify the losses? The users get too many rewards on the expense of the protocol?

**Comment by WangSecurity** [comment]
@Banditx0x @panprog could you please look at the questions I commented above. Thank you in advance.

**Comment by panprog** [comment]
@WangSecurity 
Fetch basis returns the amount of USDC if the user removes full liquidity right now (in your formula it's not USDC owned by OCL_ZVE - it's USDC in the uniswap pool, so basis = USDC in the pool * ratio of pool owned by the OCL_ZVE locker).

As for losses - from my point of view this is inflated yield at the expense of locker's principal. So, for example, normal yield for tranches is 5%, but target yield is 10%. Due to this issue, the yield for tranches might become 7% at the expense of "lost" principal in the OCL_ZVE locker even when the underlying pool price didn't change (rises then falls or falls then rises). However, the sponsor's response indicates that this is intended as this locker primarily serves to seed liquidity for protocol's ZVE token, meaning they intend for the protocol to benefit in case ZVE price rises (even if it falls in the other period)

**Comment by WangSecurity** [comment]
Thank you for that response! With that information, I believe it's indeed the intended design and the way the protocol wants to benefit from ZVE token price increasing. I agree with the escalation that this shouldn't be a duplicate of #296, but believe that it doesn't identify an issue, but a recommendation to change the protocol's design.

Hence, planning to accept the escalation, de-duplicate and invalidate this report.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [banditx0x](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/213/#issuecomment-2106431634): accepted
