### ISSUE TITLE
Matin - Unbalanced and imprecise stZVE and vestZVE token distribution occurs inside the ZivoeRewards contract due to the precision loss

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-zivoe-judging#416]
Matin

medium

# Unbalanced and imprecise stZVE and vestZVE token distribution occurs inside the ZivoeRewards contract due to the precision loss

## Summary
Less accurate stZVE and vestZVE tokens are calculated and distributed to the ZivoeRewards contract due to the priority of division over multiplication.

## Vulnerability Detail
Solidity rounds down the result of an integer division, and because of that, it is always recommended to multiply before 
dividing to avoid that precision loss. In the case of a prior division over multiplication, the final result may face serious precision loss
as the first answer would face truncated precision and then multiplied to another integer.

The problem arises in the ZivoeYDL's `distributeYield()` part. This function is responsible for distributing available yield. 
If we look deeply at this function, we can see how the allocated stZVE and vestZVE are calculated for the situation where the recipient is equal to `IZivoeGlobals_YDL(GBL).stZVE()`:

```Solidity
    function distributeYield() external nonReentrant {
        ...
            // Calculation of the protocol earnings
            else if (_recipient == IZivoeGlobals_YDL(GBL).stZVE()) {
                uint256 splitBIPS = (
                    IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() * BIPS
                ) / (
                    IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
                    IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()
                );
                uint stZVEAllocation = _protocol[i] * splitBIPS / BIPS;
                uint vestZVEAllocation = _protocol[i] * (BIPS - splitBIPS) / BIPS;
                IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
                IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).vestZVE(),vestZVEAllocation);
                IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stZVE()).depositReward(distributedAsset, stZVEAllocation);
                IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).vestZVE()).depositReward(distributedAsset, vestZVEAllocation);

        ...

            // Calculation of the residual earnings
                else if (_recipient == IZivoeGlobals_YDL(GBL).stZVE()) {
                    uint256 splitBIPS = (
                        IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() * BIPS
                    ) / (
                        IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
                        IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()
                    );
                    uint stZVEAllocation = _residual[i] * splitBIPS / BIPS;
                    uint vestZVEAllocation = _residual[i] * (BIPS - splitBIPS) / BIPS;
                    IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).stZVE(), stZVEAllocation);
                    IERC20(distributedAsset).safeIncreaseAllowance(IZivoeGlobals_YDL(GBL).vestZVE(), vestZVEAllocation);
                    IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).stZVE()).depositReward(distributedAsset, stZVEAllocation);
                    IZivoeRewards_YDL(IZivoeGlobals_YDL(GBL).vestZVE()).depositReward(distributedAsset, vestZVEAllocation);

        ...
    }
```

As it is illustrated, for the case where the recipient is `IZivoeGlobals_YDL(GBL).stZVE()`, the variables `stZVEAllocation`, and `vestZVEAllocation` are distributed to the mentioned recipient (for both
situations of protocol earnings or residual earnings).

These variables are calculated using the preceding formula: (just considering the protocol earning part that is similar to the residual earning part)

allocated stZVE formula:

$$ stZVE = \frac{protocol \ earnings \times splitBIPS}{BIPS} $$

allocated vestZVE formula:

$$ vestZVE = \frac{protocol \ earnings \times (BIPS - splitBIPS)}{BIPS} $$

At its heart, the `splitBIPS` is calculated as the division of stZVE total supply over the sum of stZVE and vestZVE total supplies:

$$ splitBIPS = \frac{stZVE \ totalSupply}{stZVE \ totalSupply + vestZVE \ totalSupply} $$

we can see in the actual implementation, there is a [hidden division before multiplication](https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L250-L257) in the calculation of the `stZVEAllocation`, and `vestZVEAllocation` that rounds down the whole expression. This is bad as the precision loss can be significant, which leads to the pool calculating less accurate `stZVE`, and `vestZVE` than actual.

At the Proof of Concept part, we can check this behavior precisely.

You can run this code to see the difference between the results:

```Solidity
    function test_precissionLoss() public {

        uint stZVEtotalSupply = IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply();
        uint vestZVEtotalSupply = IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply();

        uint256 splitBIPS = (stZVEtotalSupply * BIPS) / 
        (
            stZVEtotalSupply + 
            vestZVEtotalSupply
        );
        uint stZVEAllocation = _protocol * splitBIPS / BIPS;
        uint vestZVEAllocation = _protocol * (BIPS - splitBIPS) / BIPS;

        uint stZVEAllocation_accurate = (_protocol * stZVEtotalSupply * BIPS) / (BIPS * (stZVEtotalSupply + vestZVEtotalSupply));
        uint vestZVEAllocation_accurate = (_protocol * vestZVEtotalSupply * BIPS) / (BIPS * (stZVEtotalSupply + vestZVEtotalSupply));
        
        console.log("Current Implementation of allocated stZVE  ", stZVEAllocation);
        console.log("Current Implementation of allocated vestZVE", vestZVEAllocation);

        console.log("Accurate Implementation of allocated stZVE  ", stZVEAllocation_accurate);
        console.log("Accurate Implementation of allocated vestZVE", vestZVEAllocation_accurate);
    }
```

The result would be: 

(for these sample but real variables: 

`stZVEtotalSupply = 6.62423125 ether`, 

`vestZVEAllocation = 4.5621235125 ether`,

`_protocol = 1563214500000`
)

```Solidity

     Current Implementation of allocated stZVE  : 925579305450
     Current Implementation of allocated vestZVE: 637635194550

     Accurate Implementation of allocated stZVE  : 925689785565
     Accurate Implementation of allocated vestZVE: 637524714434 
```
Thus, we can see that the actual implementation produces **less** allocated stZVE amount and **more** allocated vestZVE amount than the precise method.
The error becomes significant especially when the protocol earning becomes bigger.

## Impact
Precision loss inside the `distributeYield()` function leads to unbalanced stZVE and vestZVE token distributions and fund loss 

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L250-L257
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/ZivoeYDL.sol#L288-L298

## Tool used

Manual Review

## Recommendation
Consider modifying the allocated tokens calculation to prevent such precision loss and prioritize multiplication over division:

```diff
            else if (_recipient == IZivoeGlobals_YDL(GBL).stZVE()) {
-                uint256 splitBIPS = (
-                    IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() * BIPS
-                ) / (
-                    IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
-                    IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()
-                );
-                uint stZVEAllocation = _protocol[i] * splitBIPS / BIPS;
-                uint vestZVEAllocation = _protocol[i] * (BIPS - splitBIPS) / BIPS;
+                uint stZVEAllocation = _protocol[i] * (IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() * BIPS) /
+                    (BIPS * (IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
+                    IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()));
+                uint vestZVEAllocation = _protocol[i] * (IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply() * BIPS) /
+                    (BIPS * (IERC20(IZivoeGlobals_YDL(GBL).stZVE()).totalSupply() + 
+                    IERC20(IZivoeGlobals_YDL(GBL).vestZVE()).totalSupply()));
```

**Comment by pseudonaut** [comment]
Valid, could optimize this further

**Comment by spacegliderrrr** [comment]
Escalate

Issue should be low, difference is only 1 basis point (0.01%). Furthermore, it is not even lost, but rather redistributed to other contract within the protocol.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Issue should be low, difference is only 1 basis point (0.01%). Furthermore, it is not even lost, but rather redistributed to other contract within the protocol. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
I'm not sure 0.01% is enough to make it medium, that's why I say it's borderline. In my opinion, since TVL can be large, the amount can still be significant.
The remark that it's not lost, but rather a distribution error between stakers and vesters is also valid, which might reduce the severity as well.
So it's up to Sherlock then, whether 0.01% is enough to make issue medium.

**Comment by MatinR1** [comment]
As mentioned by dear @panprog, the discrepancy becomes more pronounced with larger numbers. The sample numbers provided serve to highlight this disparity. When the total supplies, including protocol earnings, reach significant magnitudes, the resulting discrepancy becomes more significant. 

Additionally, it's important to acknowledge that these imprecise amounts are **continuously distributed** to stakers and vesters. Over extended periods, the cumulative discrepancy definitely exceeds 0.01%, impacting the accuracy of rewards. Therefore, after let's say 10 rounds of reward distribution, the cumulative net error surely becomes more than 0.01%.
Consequently, stakers may receive rewards that are less than expected. (The mention of "fund loss" in the report refers to this issue.)

If needed I can provide a PoC for accumulative reward distribution over a finite time frame to illustrate this issue.

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Zivoe/zivoe-core-foundry/pull/269

**Comment by RealLTDingZhen** [comment]
Just to remind, the precision loss is 0.01% of protocol yield, not TVL. If protocol has 1M to distribute, the difference is 100. I am not sure it is dust or enough for a med.

> V. How to identify a medium issue:
> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

**Comment by MatinR1** [comment]
In the Proof of Concept part, I have assumed the protocol earning is `1563214500000`, and the total supplies have a magnitude around ~1 Ether. 

In real scenarios, these numbers are significantly large, and the unbalanced amounts are continuously distributed. Additionally, the provided 1M example lacks clarity. It would be more effective to discuss the precise mathematical implications. Even if we consider the loss to be negligible, as you mentioned, this "dust" can accumulate to a substantial amount over extended periods.

**Comment by WangSecurity** [comment]
@RealLTDingZhen can you please clear this part from your last comment:

> If protocol has 1M to distribute, the difference is 100.

This is 0.0001% loss, while the real one is 0.01% and equals $10 000 from $1M to distribute. What am I missing here?

**Comment by RealLTDingZhen** [comment]
Did I make a mistake here?😂

0.01% = 1/10000

1M * 1/10000 = 1000000/10000 = 100

**Comment by WangSecurity** [comment]
Sorry, it's just I misunderstood the math here. I believe 0.01% is actually exceeding small and finite amounts, hence, medium severity is appropriate. Planning to reject the escalation and leave the issue as it is.

**Comment by deadrosesxyz** [comment]
@WangSecurity I believe it is key to remember that the 0.01% is not even lost, but simply redistributed to the protocol. Since the funds are not lost, I believe low should be more appropriate

**Comment by MatinR1** [comment]
If we consider a large time frame, these accumulated 0.01% errors (and sometimes even larger) would escalate and lead to a significantly imbalanced distribution over time. It is **mathematically** obvious that these accumulated errors would lead to a non accurate distribution.
This imprecision in distribution can cause substantial discrepancies, affecting fairness and accuracy in the system.
As this unfair distribution would cause different parties to receive imprecise funds, it should be noted that this bug is more significant than the mentioned dust amount issue and this couldn't be categorized as low.

**Comment by deadrosesxyz** [comment]
> these accumulated 0.01% errors (and sometimes even larger)

They can't be larger. Scaling is in basis points, they're 0.01% at MOST. In reality it will range from 0.00-0.01%.

> would escalate and lead to a significantly imbalanced distribution over time.

0.01% over any period of time, still remains 0.01%.

**Comment by WangSecurity** [comment]
Thank you for that remarks @deadrosesxyz and I think it'll answer your question. I see that the rewards are indeed not lost, but sent to other contracts. Still ZVE stakers receive less rewards than they should (which is what I meant with a loss) and ZVE vesters get more than they should. Yes, this issue leads to a loss of 0.01% for ZVE stakers and sometimes can be even lower. Still, this issue leads to one users receiving 0.01% rewards less (again what I mean by loss) and others 0.01% rewards more. As I've said above, 0.01% is indeed not a large number, but sufficient enough to exceed small and finite rewards to qualify for medium with high constraints. 

Decision remains the same, reject the escalation and leave the issue as it is.

**Comment by RealLTDingZhen** [comment]
So how much user loss would be considered the dividing line between med and low?😂

Also, if we really consider the loss of users after a very long period of time, this loss would be 0.005% instead of 0.01%, since

        uint256 splitBIPS = (stZVEtotalSupply * BIPS) / (stZVEtotalSupply + vestZVEtotalSupply)

The first decimal that is rounded down because of division will fluctuate randomly between 0 and 9, and the final expectation will be 5, so 0.01% would be a max cap of a single distribution, and 0.005% would be the math expectation.

**Comment by RealLTDingZhen** [comment]
So how much user loss would be considered the dividing line between med and low?😂

Also, if we really consider the loss of users after a very long period of time, this loss would be 0.005% instead of 0.01%, since

    uint256 splitBIPS = (stZVEtotalSupply * BIPS) / (stZVEtotalSupply + vestZVEtotalSupply)

The portion that is rounded down will be a random value between 0 and 1, and the expectation will be 0.5, so 0.01% would be a max cap of a single distribution, and 0.005% would be the math expectation.

**Comment by WangSecurity** [comment]
So at once, it indeed can be 0.01%, but at the long time frame, it would be 0.005% on average?

**Comment by MatinR1** [comment]
If you want to invalidate the bug anyway, there is nothing we can do with it. But it is very obvious that even these dust amounts considering %0.01 are always here and are present in each distribution. These errors would be accumulated:
For example, the difference in the first time is `9.8e8`, the second time `1.1e9`, and so on. So after let's say 10000 times of distribution, we will get a very unbalanced distribution at the order of `~1e13`. This definitely affects the fairness of the system.
I don't think it is needed to calculate complex math and probability formulas here to prove something.

Additionally, the sponsor has recognized and fixed this issue, which underscores its validity. I find it perplexing why this precision loss is being downplayed here, especially when similar issues have been accepted by Sherlock, as seen here:

https://solodit.xyz/issues/m-6-division-difference-can-result-in-a-revert-when-claiming-treasury-yield-and-excess-rewards-to-some-users-sherlock-convergence-git

**Comment by WangSecurity** [comment]
Firstly, sponsor confirming the bug and fixing it doesn't effect the final judging. Secondly, historical decisions are not sources of truth.

Watsons made a really fair remark, that in some cases it indeed may be 0 loss, and on the long timeframe it will be 0.005% on average. But, it's proven that in some cases it may cause a loss of 0.01%, which as I've said previously is enough to qualify for Medium severity. Hence, decision remains the same, reject the escalation and leave the issue as it is.

**Comment by marchev** [comment]
@WangSecurity, if a 0.01% loss warrants a valid medium severity finding, could you kindly review issue #671? The issue results in an APR loss of 0.17% for the protocol, but it has been closed as invalid.

Thank you!

**Comment by RealLTDingZhen** [comment]
Actually 0.01% is the upper limit of the loss - in any case the loss may only converge to 0.01% and not reach it. When splitBIPS is exactly divisible, the loss will be 0

**Comment by WangSecurity** [comment]
Could you please elaborate what do you mean by "only converge to 0.01% and not reach it"? As I understand the loss can indeed be 0.01% and yes I understand that it's the upper limit and in some cases it can be lower. @RealLTDingZhen

**Comment by RealLTDingZhen** [comment]
uint256 splitBIPS = (stZVEtotalSupply * BIPS) / (stZVEtotalSupply + vestZVEtotalSupply)

In extreme cases, the loss would be ( 1 - 1 / (stZVEtotalSupply + vestZVEtotalSupply) ) BIPS. 

This loss converges to 1 BIPS(0.01%) when the denominator (stZVEtotalSupply + vestZVEtotalSupply) has many decimal places.

**Comment by WangSecurity** [comment]
Thank you for explaning it. With that information and after re-reading the report and comments again, the losses are at max 0.01% and don't reach 0.01% exactly and only converge to it, i.e. always smaller than 0.01%. Moreover, there can be no loss as well and on the long time frame it's 0.005%. Lastly, the tokens are lost of Zivoe stakers and sent to Zivoe vesters, but not lost completely. With all that information, I agree with the escalation and believe the issue is indeed low severity. Planning to accept the escalation and invalidate the issue.

**Comment by MatinR1** [comment]
Dear @WangSecurity I have a question:

Keeping in mind the low error (the max cap of 0.01%), let's see what happens to stakers and vesters: (with protocol earning of ~`1e18` at each distribution):

1. The first distribution error (with 0.005%): ~`5e15`
2. The second distribution error (with 0.007%): ~`7e15`
3. Third distribution error (with 0.005%): ~`5e15`
...

Finally, as RealLTDingZhen and deadrosesxyz mentioned if we analyze with probability science, these distributions would be around 0.005% at a large time frame. But keeping in mind the total distributed amount, this 0.005% makes sense, Let's say it reaches the order of ~`1e21`. The 0.005% of this amount is ~`5e18` or 5 ethers! This 0.005% error will deviate the stakers from vester. 
With the "accumulated error" I meant this. The sum of these errors would be a meaningful amount.

Can we also say that this issue is considered low?

**Comment by deadrosesxyz** [comment]
> The first distribution error (with 0.005%): ~5e15

0.005% of 1e18 is not 5e15. It is 5e13. Reaching orders of 1e21 would result in 0.05 ethers difference.

**Comment by WangSecurity** [comment]
I might be understanding the math wrong here, but isn't the loss of 0.005% (for example) is on the ZVE stakers allocation side, not the entire reward?

But for example, there are 100_000 USDC to distribute, let's assume it's (almost) 50/50 for ZVE stakers and ZVE vesters (for simplicity). Then, each should get 50_000 USDC (50_000e18 cause it's standardizied), but with 0.005% discrepancy, ZVE stakers get 49_750e18 and ZVE vesters get 50_250e18? Is it correct?

Moreover, as I understand the rewards won't be distributed in ETH, but in stables (USDT, USDT, DAI & Frax), correct? Secondly, if we take the example with 1e21 ETH, then it's 100 ETH rewards, which sounds quite too high for rewards, no? I understand it's just an example, but I think we should be realistic here. In addition to that, to get a 0.005% loss from 100 ETH for stakers, rewards has to be > 100 ETH. Hence, this scenario seems to be unrealistic, but correct me if I'm wrong.

I understand that the higher the rewards, the larger the loss may be. But, it's relative, therefore, we measure it in percentage, rather than in the exact amount. Moreover, the loss of 0.005% (or [0;0.01%]) is on all the stakers, not on each individual one, which makes the loss for a single staker even less significant. Also, as we all agree, the loss is not guaranteed. Additionally, it's not a complete loss, but it's, of course, a loss for stakers. Lastly, as I understand the design of the protocol, there will be less and less vesters with time, therefore, the allocation to rewards will be larger and larger.

Therefore, if all my words are correct, then I believe it in fact should be low (not saying it's completely wrong of course). If something is wrong, it would be helpful if you could quote my exact words and correct them. Ultimately, I'm not saying that just a loss of 0.005% or 0.009% is small and finite to make it a low issue, my decision is based on a combination of all the factors listed above.

**Comment by Evert0x** [comment]
Will invalidate the issue in a few hours

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/416/#issuecomment-2105742456): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
