### ISSUE TITLE
Ironsidesec - It is not possible to retrieve some reward tokens ever from `OCY_Convex_C` and `OCY_Convex_A`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-zivoe-judging#506]
Ironsidesec

medium

# It is not possible to retrieve some reward tokens ever from `OCY_Convex_C` and `OCY_Convex_A`

## Summary
The issue cannot be low, but medium because the roles of external integration are restricted. So, the `rewardManager` role of `convex` contracts are not trusted. They have the power to add or remove the reward tokens from the convex reward contarcts. So if they remove any reward tokens before the `OCY_Convex_C` claims its rewards, then these rewards are wasted permanently on `OCY_Convex_C` and `OCY_Convex_A`.

Look at the simple recommendation that can solve this issue.
It is not possible to retrieve some tokens ever. It is due to the lack of feature to move tokens from locker to YDL / DAO.

## Vulnerability Detail

From https://github.com/sherlock-audit/2024-03-zivoe?tab=readme-ov-file#q-are-the-admins-of-the-protocols-your-contracts-integrate-with-if-any-trusted-or-restricted

```md
Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?

RESTRICTED
```

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L200-L220

```solidity

File: 2024-03-zivoe\zivoe-core-foundry\src\lockers\OCY\OCY_Convex_C.sol

200:     function claimRewards(bool extra) public nonReentrant {
201:         IBaseRewardPool_OCY_Convex_C(convexRewards).getReward();
202:
203:         // Native Rewards (CRV, CVX)
204:         uint256 rewardsCRV = IERC20(CRV).balanceOf(address(this));
205:         uint256 rewardsCVX = IERC20(CVX).balanceOf(address(this));
206:         if (rewardsCRV > 0) { IERC20(CRV).safeTransfer(OCT_YDL, rewardsCRV); }
207:         if (rewardsCVX > 0) { IERC20(CVX).safeTransfer(OCT_YDL, rewardsCVX); }
208:
209:         // Extra Rewards
210:         if (extra) {
211:            
212:             uint256 extraRewardsLength = IBaseRewardPool_OCY_Convex_C(convexRewards).extraRewardsLength();
213:             for (uint256 i = 0; i < extraRewardsLength; i++) {
214:  >>>            address rewardContract = IBaseRewardPool_OCY_Convex_C(convexRewards).extraRewards(i);
215:  >>>            uint256 rewardAmount = IBaseRewardPool_OCY_Convex_C(rewardContract).rewardToken().balanceOf(
216:                     address(this)
217:                 );
218:                 if (rewardAmount > 0) { IERC20(rewardContract).safeTransfer(OCT_YDL, rewardAmount); }
219:                
220:             }
221:         }
222:     }

```

**Issue path:**

1. The `rewardManager` which is a restricted external  role of `convexRewards`, will add/remove a new reward token and it will stream new reward tokens for may be 7 days or even 2 - 4 weeks. And after a while, that reward token can be removed by that manager.

scroll a bit after going to https://etherscan.io/address/0xc583e81bB36A1F620A804D8AF642B63b0ceEb5c0#code#L835

![image](https://github.com/sherlock-audit/2024-03-zivoe-ironsidesec/assets/162350329/ba1353dd-a7ac-4bd7-a084-8e4f5223d645)

2. But `claimRewards`  was not called in any of these times so reward is not claimed, or maybe the reward manager has called `clearExtraRewards` before this claimreward call, which will remove the reward token. So there's no way `OCY_Convex_C` can claim reward except someone will call `getReward` externally with `OCY_Convex_C` as input address, and reward pending tokens will be transfered.

3. Still, the tokens cannot be transferred to YDL because the token addresses are called from line 214 above, which can be manipulated by `rewardManager`. so effectively wasted rewards.

## Impact
Loss of reward tokens in 2 convex integration contracts A and C. So medium.

## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L200-L220

https://github.com/sherlock-audit/2024-03-zivoe/blob/01e00e6f27b58392a6fa0b82c84a46a783a0df3c/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L246

## Tool used

Manual Review

## Recommendation

Add the below function to both `OCY_Convex_C` and `OCY_Convex_A` contracts. So if there's any extra reward token in these contracts, they can be transferred out.

```solidity
    function canPullMulti() public override pure returns (bool) { return true; }

```

**Comment by pseudonaut** [comment]
Not of concern

**Comment by spacegliderrrr** [comment]
Escalate

Issue should be low. Lack of contract functionality is not an issue according to Sherlock rules. Contract will work as expected upon deployment.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Issue should be low. Lack of contract functionality is not an issue according to Sherlock rules. Contract will work as expected upon deployment.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
It's not lack of functionality, it's a loss of reward funds due to external integrated protocol's admin removing reward tokens from the pool - the reward will be stuck (lost) in the locker in such case.

**Comment by RealLTDingZhen** [comment]
This one should be a LOW. 

In the current convex-C, the only ExtraReward is the same as the pooltoken and can be taken away with `pullfromlocker`. So this is actually a future issue with low likelihood.

And, it is a Zivoe admin mistake to not harvest and distribute yields in advance. If all other convex admin issues are invalidated, this should also be invalidated.

**Comment by panprog** [comment]
While likelihood is low, it's still possible. It doesn't matter if reward token is currently the same as pool token (didn't verify this, is it really so?). The fact is that external admin can add reward token, which will accumulate, but then external admin removes the reward token midway through the 30-days period, so that zivoe admins don't have time to react to this.

**Comment by retsoko** [comment]
This is indeed a future issue with low likelihood. However it is unrealistic to expect Zivoe admins to constantly monitor all integrated convex pools to prevent the situation described in the report.

**Comment by joicygiore** [comment]
> While likelihood is low, it's still possible. It doesn't matter if reward token is currently the same as pool token (didn't verify this, is it really so?). The fact is that external admin can add reward token, which will accumulate, but then external admin removes the reward token midway through the 30-days period, so that zivoe admins don't have time to react to this.

respected

**Comment by RealLTDingZhen** [comment]
> While likelihood is low, it's still possible. It doesn't matter if reward token is currently the same as pool token (didn't verify this, is it really so?). The fact is that external admin can add reward token, which will accumulate, but then external admin removes the reward token midway through the 30-days period, so that zivoe admins don't have time to react to this.

Sorry for the ambiguous, actually its [CVX](https://etherscan.io/address/0x6dF312B6367F53e4b7875738d32DE7925A72a1CF#readContract#F16) and [PYUSD](https://etherscan.io/address/0x22A0a706Aa423E2257e4217be2268e0374b9229f#readContract#F16).

CVX can be normally received, and PYUSD can be pulled out by DAO.

**Comment by IronsideSec** [comment]
As the judge points out, the convex manager is an external restricted admin (acc to contest Readme) So any action  convex manager can perform that affects Zivoe should be considered impactful (loss of rewards) irrespective of the likelihood. 

Regarding the comments about the low likelihood of this event :
Some past findings from Sherlock contests (listed below) assumed malicious intent by restricted admins of external integrations, (like private key loss, and contract upgrades) which is far less probable, and those issues were still accepted as valid.
This issue is more valid than the below ones because, it arises even when the admin of the integrated protocol has good intentions, making it a more realistic and likely scenario than the below issues.

1. https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/862, 
2. https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/570, 
3. https://github.com/sherlock-audit/2024-01-napier-judging/issues/108

**Comment by WangSecurity** [comment]
Firstly, historical decision are not sources of truth under Sherlock's rules.

Secondly, I don't really understand why some watsons say it's "future issue", could you please explain it in a bit greater detail @RealLTDingZhen and @retsoko?

Lastly, don't clearly understand this line:

> So there's no way OCY_Convex_C can claim reward except someone will call getReward externally with OCY_Convex_C as input address, and reward pending tokens will be transfered.

So the reward tokens can be withdrawn from the contract if this issue occurs or not? Or it refers only to extra rewards?

**Comment by IronsideSec** [comment]
> So there's no way OCY_Convex_C can claim reward except someone will call getReward externally with OCY_Convex_C as input address, and reward pending tokens will be transfered.

@WangSecurity 
 Its referring to extraRewards.  And `OCY_Convex_C ` knows what are the reward tokens only by calling the array `extraRewards`. This array can be updated by convex manager at will.
But even if he removes this reward token from array, anyone can call convex reward contract and it will transfer those rewards to  `OCY_Convex_C `. But `OCY_Convex_C ` lacks functionality to move those rewards due to lack of `canPullMulti` function implementation.

So rewards are locked in `OCY_Convex_C ` . Escalating Watson is saying `future issue` because this issue depends on future actions of convex reward manager. But according to Sherlock readme : `convex reward manager is restricted role` and he can remove any reward token causing loss to Zivoe.

https://github.com/sherlock-audit/2024-03-zivoe#q-are-the-admins-of-the-protocols-your-contracts-integrate-with-if-any-trusted-or-restricted

```md
Q: Are the admins of the protocols your contracts integrate with (if any) TRUSTED or RESTRICTED?
RESTRICTED
```

**Comment by panprog** [comment]
@WangSecurity 

> Secondly, I don't really understand why some watsons say it's "future issue"

They said future issue, because it will come up if in the future the admin will:
1. Add some extra reward token
2. Then after some time remove this extra reward token

I don't think this makes it a "future issue" since these are valid external admin actions.

> Lastly, don't clearly understand this line:
> 
> > So there's no way OCY_Convex_C can claim reward except someone will call getReward externally with OCY_Convex_C as input address, and reward pending tokens will be transfered.
> 
> So the reward tokens can be withdrawn from the contract if this issue occurs or not? Or it refers only to extra rewards?

This is what can happen:
1. There is extra reward X in the convex pool (which is address with a `Rewards` contract)
2. `OCY_Convex_C` locker's deposit accumulates some of this reward
3. External rewards admin removes extra reward X from the convex pool.
4. The `OCY_Convex_C.claimReward` will now be unable to claim the reward X, because it claims via the convex pool, which doesn't have X anymore.
5. However, it's still possible for anyone to call `X.claimRewards(locker_address)`, because this function is persmissionless, it simply transfers reward token accumulated by given address to this address. So if locker admin calls this, the reward token is transferred to OCY_Convex_C locker address.
6. However, the only function to pull token from this locker only allows pulling the convex pool's asset:
```solidity
        require(asset == convexPoolToken, "OCY_Convex_C::pullFromLocker() asset != convexPoolToken");
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Zivoe/zivoe-core-foundry/pull/267

**Comment by RealLTDingZhen** [comment]
Hey @panprog @WangSecurity It seems this issue is actually incorrect.

A convex pool's ExtraRewards cannot be removed.

Please check the `BaseRewardPool` of convex pool 270(OCY_Convex_C):

https://etherscan.io/address/0xc583e81bB36A1F620A804D8AF642B63b0ceEb5c0#readContract#F15

The reward manager is set to Convex Reward Factory: https://etherscan.io/address/0xEdCCB35798fae4925718A43cc608aE136208aa8D

And, if you check the code, you'll notice that there is no function that removes the `ExtraReward`:

https://github.com/convex-eth/platform/blob/main/contracts/contracts/RewardFactory.sol

```solidity
    function removeActiveReward(address _reward, uint256 _pid) external returns(bool){
        require(rewardAccess[msg.sender] == true,"!auth");
        if(_reward == address(0)){
            return true;
        }

        uint256[] storage activeList = rewardActiveList[_reward];
        uint256 pid = _pid+1; //offset by 1 so that we can use 0 as empty

        uint256 length = activeList.length;
        for(uint256 i = 0; i < length; i++){
            if(activeList[i] == pid){
                if (i != length-1) {
                    activeList[i] = activeList[length-1];
                }
                activeList.pop();
                break;
            }
        }
        return true;
    }
```

Extrarewards are only removed inside `RewardFactory`, and they just stop provide the reward for `BaseRewardPool`. So it seems Convex is aware of such issue in external integration. I think the reason convex kept [this function](https://etherscan.io/address/0xc583e81bB36A1F620A804D8AF642B63b0ceEb5c0#code#L835) is that the entire contract was copied from Synthetix and they wanted to keep the interface.

**Comment by WangSecurity** [comment]
Thank you @RealLTDingZhen and your analysis looks extremely correct. `clearExtraRewards` can be called only by its manager which is a contract with lack of functionality to call this function, correct? Also tagging @panprog and @ironsidesec to provide counter arguments.

**Comment by panprog** [comment]
Great catch by @RealLTDingZhen ! Yes, it's indeed not possible to clear the extra rewards. Agree that this issue should be invalid then.

**Comment by WangSecurity** [comment]
Since the issue described in the report is impossible, planning to accept the escalation and invalidate the issue.

**Comment by ZdravkoHr** [comment]
@WangSecurity, you mean accept the escalation, right?

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-03-zivoe-judging/issues/506/#issuecomment-2105741414): accepted

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
