### ISSUE TITLE
eeshenggoh - claimReward() does claim the extra rewards even if boolean is false

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-zivoe-judging#8]
eeshenggoh

medium

# claimReward() does claim the extra rewards even if boolean is false

## Summary
The lockers can claim rewards and forward them to the OCT_YDL.  The problem lies in the implementation of calling the convex `getRewards()`
## Vulnerability Detail
For LP tokens, CVX, or cvxCRV staking: `BaseRewardPool.getReward(user, claimExtras=true)` claimExtras determines whether the user wants to withdraw his extraRewards tokens. The problem lies in calling `getReward()` which also claimExtra rewards by default.

From this address we can check the following function `address public convexRewards = 0x26598e3E511ADFadefD70ab2C3475Ff741741104;`

https://etherscan.io/address/0x26598e3E511ADFadefD70ab2C3475Ff741741104#code#L998
```solidity
    function getReward() external returns(bool){ // @audit-issue this sets claimExtras=true
        getReward(msg.sender,true);
        return true;
    }
    function getReward(address _account, bool _claimExtras) public updateReward(_account) returns(bool){
        uint256 reward = earned(_account);
        if (reward > 0) {
            rewards[_account] = 0;
            rewardToken.safeTransfer(_account, reward);
            IDeposit(operator).rewardClaimed(pid, _account, reward);
            emit RewardPaid(_account, reward);
        }

        //also get rewards from linked rewards
        if(_claimExtras){
            for(uint i=0; i < extraRewards.length; i++){
                IRewards(extraRewards[i]).getReward(_account);
            }
        }
        return true;
    }

```
## Impact
Extra rewards are claimed regardless of boolean input
## Code Snippet
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_A.sol#L247
https://github.com/sherlock-audit/2024-03-zivoe/blob/main/zivoe-core-foundry/src/lockers/OCY/OCY_Convex_C.sol#L201
## Tool used

Manual Review

## Recommendation
Instead of using `getReward()`, include `getReward(address(this),false)`
```diff
++  IBaseRewardPool_OCY_Convex_A(convexRewards).getReward(address(this),false);
--  IBaseRewardPool_OCY_Convex_A(convexRewards).getReward();
```
```diff
++ IBaseRewardPool_OCY_Convex_C(convexRewards).getReward(address(this),false);
-- IBaseRewardPool_OCY_Convex_C(convexRewards).getReward();
```

**Comment by pseudonaut** [comment]
This doesn't appear valid

**Comment by goheesheng** [comment]
escalate 
It should at least be a medium because according to Sherlock's Rule: `Breaks core contract functionality`. The function contract of `getReward()` was to get extra rewards using the boolean. **However**, regardless of the **admin input**, rewards will always be sent to YDL without **admins boolean permission.**

**Comment by sherlock-admin3** [comment]
> escalate 
> It should at least be a medium because according to Sherlock's Rule: `Breaks core contract functionality`. The function contract of `getReward()` was to get extra rewards using the boolean. **However**, regardless of the **admin input**, rewards will always be sent to YDL without **admins boolean permission.**

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by panprog** [comment]
It doesn't say it claims reward in underlying pool, it just sends to YDL if this flag is true, which works as intended. I also don't think this is core functionality because there is no impact even if the extra reward is claimed when the flag is false - yes, it might not be what is expected, but nothing bad happens due to it, no impact - thus it's low.

**Comment by goheesheng** [comment]
> It doesn't say it claims reward in underlying pool, it just sends to YDL if this flag is true, which works as intended. I also don't think this is core functionality because there is no impact even if the extra reward is claimed when the flag is false - yes, it might not be what is expected, but nothing bad happens due to it, no impact - thus it's low.

"It doesn't say it claims reward in underlying pool, it just sends to YDL if this flag is true, which works as intended." This does not work as intended. When the admin sets the flag to false, the intention is to not send the extra rewards yield to YDL, however regardless of boolean to be false, it will be sent to the YDL. 

If extra rewards were to be claimed every iteration, lesser extra rewards will be claimed than the admin were to claim them in one go.

According to the [Convex Docs](https://docs.convexfinance.com/convexfinanceintegration/baserewardpool):

"""
A staking implementation example handling these wrappers can be found at: https://github.com/convex-eth/platform/blob/main/contracts/contracts/wrappers/ConvexStakingWrapper.sol
"""
[ _claimExtras is used to claim extra rewards](https://github.com/convex-eth/platform/blob/46888db798227cb49902816db29e664ff9df60e7/contracts/contracts/wrappers/ConvexStakingWrapper.sol#L377). You can see that [_calcRewardIntegral will be used within the _checkpoint](https://github.com/convex-eth/platform/blob/46888db798227cb49902816db29e664ff9df60e7/contracts/contracts/wrappers/ConvexStakingWrapper.sol#L288). Within all the functions, the most crucial [line](https://github.com/convex-eth/platform/blob/46888db798227cb49902816db29e664ff9df60e7/contracts/contracts/wrappers/ConvexStakingWrapper.sol#L313) shows that rewards added and calculated everytime is called will return lesser extra rewards because of the multiplication factor. Simple E.g. if 1 x 2 = 2, while 2 x 2 = 4. 

To conclude, if protocol doesn't fix this issue, lesser extra rewards will be provided than claiming it one go or specified by the admin in boolean.

**Comment by BiasedMerc** [comment]
In your example:

>> Simple E.g. if 1 x 2 = 2, while 2 x 2 = 4.

You are not accounting for the previously retrieved rewards..

It would be either

Retrieve 2 times: (1x2)+(1x2) = 4
Retrieve once: 2x2 = 4

So it doesn't have an effect
